# Generated by Django 4.0 on 2021-12-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_is_special_alter_article_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0004_rename_user_userbase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBase',
            new_name='User',
        ),
    ]
