# Generated by Django 4.0 on 2021-12-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_is_special_alter_article_status'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comment', '0013_alter_blockeduser_id_alter_blockeduserhistory_id_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0007_rename_nob_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='NewUser',
        ),
    ]
