# Generated by Django 4.0 on 2021-12-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
